version: '2'
services:
  tresxtres-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/TresXtres/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=TresXtres
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
